name: Build Ambari

on:
  push:
    branches:
      - clemlab-2.7.8.0
  pull_request:
    branches:
      - clemlab-2.7.8.0

jobs:
  build:
    runs-on: [ self-hosted, Linux, X64, ubuntu ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y maven openjdk-8-jdk python2-dev bzip2 git gcc
          sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac

      - name: Build ambari
        run: |
          java -version && python2 -V
          mvn -B install package jdeb:jdeb "-Dmaven.clover.skip=true" "-DskipTests" "-Dstack.distribution=ODP" \
          "-Drat.ignoreErrors=true" -Dpython.ver="python >= 2.6" -Djdk.version="1.8" -Dfindbugs.skip=true \
          -DbuildNumber=$(git rev-parse HEAD) -Dviews -Pdeb "-Dodp.release.number=134"

      - name: Copy Ambari debs
        if: github.event_name == 'push' && github.ref == 'refs/heads/clemlab-2.7.8.0'
        run: |
          mkdir debs
          cp ambari-agent/target/ambari-agent_*.deb debs
          cp ambari-server/target/ambari-server_*.deb debs
          cp contrib/views/ambari-views-package/target/ambari-views-package_*.deb debs
          cp ambari-logsearch/ambari-logsearch-assembly/target/ambari-logsearch-portal_*.deb debs
          cp ambari-logsearch/ambari-logsearch-assembly/target/ambari-logsearch-logfeeder_*.deb debs
          cp ambari-metrics/ambari-metrics-assembly/target/ambari-metrics-assembly_*.deb debs
          cp ambari-infra/ambari-infra-assembly/target/ambari-infra-manager_*.deb debs
          cp ambari-infra/ambari-infra-assembly/target/ambari-infra-solr-client_*.deb debs
          cp ambari-infra/ambari-infra-assembly/target/ambari-infra-solr_*.deb debs

      - name: Upload artifact on GH
        if: github.event_name == 'push' && github.ref == 'refs/heads/clemlab-2.7.8.0'
        uses: actions/upload-artifact@v4
        with:
          name: ambari-artifacts
          path: ./debs

  upload-artifacts:
    runs-on: [ self-hosted, Linux, X64, ubuntu ]
    environment: production
    if: github.event_name == 'push' && github.ref == 'refs/heads/clemlab-2.7.8.0'
    needs: build
    steps:
      - name: Download artifact from GH
        uses: actions/download-artifact@v4
        with:
          name: ambari-artifacts
          path: ./debs

      - name: Upload Ambari debs on Nexus
        run: |
          for deb_file in debs/*.deb; do curl -u "${{ secrets.NEXUS_USER_CREDENTIALS }}" -H "Content-Type: multipart/form-data" --data-binary "@./$deb_file" "${{ secrets.NEXUS_APT_REPO_URL }}"; done
